Repository ivandi1980/to-react-hilla, pull requests merged in 2023-02, with the labels that each got.

#1 clean up!
  frontend/views/MainLayout.module.css
  frontend/views/MainLayout.tsx
  frontend/views/TodoView.tsx
  frontend/views/about/AboutView.tsx
  frontend/views/helloreact/HelloReactView.tsx
  package-lock.json
Labels: enhancement

#3 endpoint created!
  README.md
  mvnw
  src/main/java/com/example/application/endpoints/TodoEndpoint.java
  src/main/java/com/example/application/endpoints/helloreact/HelloReactEndpoint.java
Labels: enhancement

#5 Readme Updated!
  README.md
Labels: documentation

#7 added image
  README.md
  frontend/views/TodoView.tsx
  src/main/resources/Assets/Hilla.png
Labels: bug, documentation, enhancement

#9 Readme updated!
  README.md
Labels: documentation
